version: "3.9"

services:
  aplikuha:
    image: films1
    build: .

    environment:
      MAX_FILMS: 5
      DATA_FILE_PATH: "./films.json"

    ports:
      # port outside : port inside
      - 8081:8080
